In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

In [4]:
df = pd.read_csv('cars_dataset.csv')

In [22]:
df

       brand  km_driven    fuel         owner  selling_price
0      Skoda     133038  Diesel  Second Owner         593000
1     Maruti     194721  Petrol   First Owner         694000
2     Toyota      14213  Diesel  Second Owner         458000
3       Tata      69210  Diesel   First Owner        1134000
4       Ford      10406  Diesel   First Owner         750000
...      ...        ...     ...           ...            ...
7995   Honda     190278  Diesel  Second Owner         472000
7996  Maruti     247121  Diesel   First Owner         463000
7997     BMW     233891  Diesel   First Owner         865000
7998    Ford     274303  Petrol  Second Owner         649000
7999  Nissan     225249  Petrol   First Owner         230000

[8000 rows x 5 columns]

In [6]:
df['owner'].value_counts()

owner
First Owner             5206
Second Owner            2072
Third Owner              546
Fourth & Above Owner     171
Test Drive Car             5
Name: count, dtype: int64

In [7]:
df['brand'].unique()

array(['Skoda', 'Maruti', 'Toyota', 'Tata', 'Ford', 'Mitsubishi', 'Jeep',
       'BMW', 'Renault', 'Volkswagen', 'MG', 'Chevrolet', 'Audi',
       'Nissan', 'Honda', 'Hyundai', 'Kia', 'Mahindra', 'Fiat',
       'Mercedes'], dtype=object)

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
                                                    df.drop(columns=['selling_price']),
                                                    df['selling_price'], 
                                                    test_size=0.2, 
                                                    random_state=42
                                                )

In [9]:
# Applying Ordinal Encoder on Owner
oe = OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']])

X_train_owner = oe.fit_transform(X_train.loc[:, ['owner']])
X_test_owner = oe.transform(X_test.loc[:, ['owner']])

In [10]:
# Jab OrdinalEncoder encode karta hai, result aata hai as a NumPy Array:
# Convert array to df 
X_train_owner_df = pd.DataFrame(X_train_owner, columns=oe.get_feature_names_out())
X_test_owner_df = pd.DataFrame(X_test_owner, columns=oe.get_feature_names_out())

In [11]:
X_train_owner_df.head()

   owner
0    4.0
1    3.0
2    4.0
3    3.0
4    4.0

In [12]:
# Applying the OHE on 'brand' and 'fuel'  
ohe = OneHotEncoder(sparse_output=False)

X_train_brand_fuel = ohe.fit_transform(X_train[['brand', 'fuel']])
X_test_brand_fuel = ohe.fit_transform(X_test[['brand', 'fuel']])

In [13]:
# Converting into dataframe
X_train_brand_fuel_df = pd.DataFrame(X_train_brand_fuel, columns=ohe.get_feature_names_out())
X_test_brand_fuel_df = pd.DataFrame(X_test_brand_fuel, columns=ohe.get_feature_names_out())

In [14]:
print(X_train_brand_fuel.shape)          # how many cols in data?
print(len(ohe.get_feature_names_out()))  # how many col names?

(6400, 24)
24

In [15]:
X_train_brand_fuel_df.head()

,brand_Audi,brand_BMW,brand_Chevrolet,brand_Fiat,brand_Ford,brand_Honda,brand_Hyundai,brand_Jeep,brand_Kia,brand_MG,...,brand_Nissan,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [16]:
X_train.head()

           brand  km_driven    fuel         owner
1467   Chevrolet     289443  Petrol   First Owner
5768  Mitsubishi     154046  Petrol  Second Owner
5714        Jeep      27543  Diesel   First Owner
1578     Renault     210225  Petrol  Second Owner
6958  Mitsubishi      55332  Petrol   First Owner

In [17]:
# To delete the column of 'brand, 'fuel' and 'owner' from original df
X_train_rem = X_train.drop(columns=['brand', 'fuel', 'owner'], inplace=True)
X_test_rem = X_test.drop(columns=['brand', 'fuel', 'owner'], inplace=True)

In [18]:
X_train_rem

In [19]:
# concat the Encoded col to original df
X_train = pd.concat([X_train_rem, X_train_owner_df, X_train_brand_fuel_df], axis=1)
X_test = pd.concat([X_test_rem, X_test_owner_df, X_test_brand_fuel_df], axis=1)

In [20]:
X_train

,owner,brand_Audi,brand_BMW,brand_Chevrolet,brand_Fiat,brand_Ford,brand_Honda,brand_Hyundai,brand_Jeep,brand_Kia,...,brand_Nissan,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6396,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6397,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6398,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6399,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [21]:
# This process is very hectic to perfrom on big col data, to replace this, Here's comes "Column Transfromer" its very helpful to perfrom different Encoding on column at a time and at the end "marge" them

In [23]:
# datatype 

a = None 
type(a)

NoneType

In [24]:
def add_two_numbers(a,b):
      print(f'Sum of {a} and {b} is {a + b}')

In [26]:
c = add_two_numbers(4, 6)

Sum of 4 and 6 is 10

In [27]:
print(c)

None

In [34]:
def add_two_number(a, b):
      res = a + b
      print(f'Sum of {a} and {b} is {res}')
      return res

In [35]:
add_two_number(5, 6)

Sum of 5 and 6 is 11

11