In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('cars_dataset.csv')

In [3]:
df

       brand  km_driven    fuel         owner  selling_price
0      Skoda     133038  Diesel  Second Owner         593000
1     Maruti     194721  Petrol   First Owner         694000
2     Toyota      14213  Diesel  Second Owner         458000
3       Tata      69210  Diesel   First Owner        1134000
4       Ford      10406  Diesel   First Owner         750000
...      ...        ...     ...           ...            ...
7995   Honda     190278  Diesel  Second Owner         472000
7996  Maruti     247121  Diesel   First Owner         463000
7997     BMW     233891  Diesel   First Owner         865000
7998    Ford     274303  Petrol  Second Owner         649000
7999  Nissan     225249  Petrol   First Owner         230000

[8000 rows x 5 columns]

In [4]:
df['owner'].value_counts()

owner
First Owner             5206
Second Owner            2072
Third Owner              546
Fourth & Above Owner     171
Test Drive Car             5
Name: count, dtype: int64

In [5]:
df['brand'].unique()

array(['Skoda', 'Maruti', 'Toyota', 'Tata', 'Ford', 'Mitsubishi', 'Jeep',
       'BMW', 'Renault', 'Volkswagen', 'MG', 'Chevrolet', 'Audi',
       'Nissan', 'Honda', 'Hyundai', 'Kia', 'Mahindra', 'Fiat',
       'Mercedes'], dtype=object)

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
                                                    df.drop(columns=['selling_price']),
                                                    df['selling_price'], 
                                                    test_size=0.2, 
                                                    random_state=42
                                                )

In [7]:
# Applying Ordinal Encoder on Owner
oe = OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']])

X_train_owner = oe.fit_transform(X_train.loc[:, ['owner']])
X_test_owner = oe.transform(X_test.loc[:, ['owner']])

In [8]:
# Jab OrdinalEncoder encode karta hai, result aata hai as a (NumPy Array):
# Convert array to df 
X_train_owner_df = pd.DataFrame(X_train_owner, columns=oe.get_feature_names_out())
X_test_owner_df = pd.DataFrame(X_test_owner, columns=oe.get_feature_names_out())

In [9]:
X_train_owner_df.head()

   owner
0    4.0
1    3.0
2    4.0
3    3.0
4    4.0

In [10]:
# Applying the OHE on 'brand' and 'fuel'  
ohe = OneHotEncoder(sparse_output=False)

X_train_brand_fuel = ohe.fit_transform(X_train[['brand', 'fuel']])
X_test_brand_fuel = ohe.transform(X_test[['brand', 'fuel']])

In [11]:
# Converting into dataframe
X_train_brand_fuel_df = pd.DataFrame(X_train_brand_fuel, columns=ohe.get_feature_names_out())
X_test_brand_fuel_df = pd.DataFrame(X_test_brand_fuel, columns=ohe.get_feature_names_out())

In [12]:
print(X_train_brand_fuel.shape)          # how many cols in data?
print(len(ohe.get_feature_names_out()))  # how many col names?

(6400, 24)
24

In [13]:
X_train_brand_fuel_df.head()

,brand_Audi,brand_BMW,brand_Chevrolet,brand_Fiat,brand_Ford,brand_Honda,brand_Hyundai,brand_Jeep,brand_Kia,brand_MG,...,brand_Nissan,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [14]:
X_train.head()

           brand  km_driven    fuel         owner
1467   Chevrolet     289443  Petrol   First Owner
5768  Mitsubishi     154046  Petrol  Second Owner
5714        Jeep      27543  Diesel   First Owner
1578     Renault     210225  Petrol  Second Owner
6958  Mitsubishi      55332  Petrol   First Owner

In [15]:
# To delete the column of 'brand, 'fuel' and 'owner' from original df
X_train_rem = X_train.drop(columns=['brand', 'fuel', 'owner'], inplace=True)
X_test_rem = X_test.drop(columns=['brand', 'fuel', 'owner'], inplace=True)

In [16]:
X_train_rem

In [17]:
# concat the Encoded col to original df
X_train = pd.concat([X_train_rem, X_train_owner_df, X_train_brand_fuel_df], axis=1)
X_test = pd.concat([X_test_rem, X_test_owner_df, X_test_brand_fuel_df], axis=1)

In [18]:
X_train

,owner,brand_Audi,brand_BMW,brand_Chevrolet,brand_Fiat,brand_Ford,brand_Honda,brand_Hyundai,brand_Jeep,brand_Kia,...,brand_Nissan,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol
0,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6395,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6396,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
6397,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
6398,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
6399,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

## The Easy Way!

In [19]:
# This process is very hectic to perfrom on big col data, to replace this, Here's comes "Column Transfromer" its very helpful to perfrom different Encoding on column at a time and at the end "marge" them

In [ ]:
from sklearn.compose import ColumnTransformer

In [21]:
df = pd.read_csv('cars_dataset.csv')
df.head()

    brand  km_driven    fuel         owner  selling_price
0   Skoda     133038  Diesel  Second Owner         593000
1  Maruti     194721  Petrol   First Owner         694000
2  Toyota      14213  Diesel  Second Owner         458000
3    Tata      69210  Diesel   First Owner        1134000
4    Ford      10406  Diesel   First Owner         750000

In [22]:
X_train, X_test, y_train, y_test = train_test_split(
                                                      df.drop(columns=['selling_price']),
                                                      df['selling_price'],
                                                      test_size=0.2,
                                                      random_state=42
                                                   )

In [23]:
X_train.head()

           brand  km_driven    fuel         owner
1467   Chevrolet     289443  Petrol   First Owner
5768  Mitsubishi     154046  Petrol  Second Owner
5714        Jeep      27543  Diesel   First Owner
1578     Renault     210225  Petrol  Second Owner
6958  Mitsubishi      55332  Petrol   First Owner

In [24]:
# ColumnTransformer(
#       [
#           ("name1", object/encoding[col1, col2]),
#           ( ),
#           ( )
#       ]
# )

# this the flow to create ColumnTransformer

In [25]:
transformers = ColumnTransformer(
      [
            ("ordinal", OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner', 'Third Owner', 'Second Owner', 'First Owner']]),['owner']),
            ("onehot", OneHotEncoder(sparse_output=False), ['brand', 'fuel'])
      ],  
      remainder='passthrough'  #it means ki baki col mein kuch ni karna, as it is pass hone do  
)

# setting to get a direct pandas df (quick method)
transformers.set_output(transform='pandas')

ColumnTransformer(remainder='passthrough',
                  transformers=[('ordinal',
                                 OrdinalEncoder(categories=[['Test Drive Car',
                                                             'Fourth & Above '
                                                             'Owner',
                                                             'Third Owner',
                                                             'Second Owner',
                                                             'First Owner']]),
                                 ['owner']),
                                ('onehot', OneHotEncoder(sparse_output=False),
                                 ['brand', 'fuel'])])

In [26]:
X_train_transformed = transformers.fit_transform(X_train)
X_test_transformed = transformers.transform(X_train)

In [27]:
# pd.DataFrame(X_train_transformed, columns=transformers.get_feature_names_out())
# pd.DataFrame(X_test_transformed, columns=transformers.get_feature_names_out())

In [28]:
X_train_transformed

,ordinal__owner,onehot__brand_Audi,onehot__brand_BMW,onehot__brand_Chevrolet,onehot__brand_Fiat,onehot__brand_Ford,onehot__brand_Honda,onehot__brand_Hyundai,onehot__brand_Jeep,onehot__brand_Kia,...,onehot__brand_Renault,onehot__brand_Skoda,onehot__brand_Tata,onehot__brand_Toyota,onehot__brand_Volkswagen,onehot__fuel_CNG,onehot__fuel_Diesel,onehot__fuel_LPG,onehot__fuel_Petrol,remainder__km_driven
1467,4.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,289443
5768,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,154046
5714,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,27543
1578,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,210225
6958,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,55332
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5226,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,23660
5390,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,223625
860,4.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,48224
7603,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,96663
7270,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,269071

In [29]:
# there's some attributes to check final output
transformers.feature_names_in_

array(['brand', 'km_driven', 'fuel', 'owner'], dtype=object)

In [30]:
# 02
transformers.get_feature_names_out()

array(['ordinal__owner', 'onehot__brand_Audi', 'onehot__brand_BMW',
       'onehot__brand_Chevrolet', 'onehot__brand_Fiat',
       'onehot__brand_Ford', 'onehot__brand_Honda',
       'onehot__brand_Hyundai', 'onehot__brand_Jeep', 'onehot__brand_Kia',
       'onehot__brand_MG', 'onehot__brand_Mahindra',
       'onehot__brand_Maruti', 'onehot__brand_Mercedes',
       'onehot__brand_Mitsubishi', 'onehot__brand_Nissan',
       'onehot__brand_Renault', 'onehot__brand_Skoda',
       'onehot__brand_Tata', 'onehot__brand_Toyota',
       'onehot__brand_Volkswagen', 'onehot__fuel_CNG',
       'onehot__fuel_Diesel', 'onehot__fuel_LPG', 'onehot__fuel_Petrol',
       'remainder__km_driven'], dtype=object)

In [31]:
# 03- how many features are transformed
transformers.n_features_in_

4

In [32]:
transformers.transformers_

[('ordinal',
  OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                              'Third Owner', 'Second Owner', 'First Owner']]),
  ['owner']),
 ('onehot', OneHotEncoder(sparse_output=False), ['brand', 'fuel']),
 ('remainder',
  FunctionTransformer(accept_sparse=True, check_inverse=False,
                      feature_names_out='one-to-one'),
  [1])]

In [33]:
# 04 - how many operations are performed in transformer, show in dict
transformers.named_transformers_

{'ordinal': OrdinalEncoder(categories=[['Test Drive Car', 'Fourth & Above Owner',
                             'Third Owner', 'Second Owner', 'First Owner']]),
 'onehot': OneHotEncoder(sparse_output=False),
 'remainder': FunctionTransformer(accept_sparse=True, check_inverse=False,
                     feature_names_out='one-to-one')}

In [34]:
# also extract the particular information
transformers.named_transformers_['ordinal'].categories_

[array(['Test Drive Car', 'Fourth & Above Owner', 'Third Owner',
        'Second Owner', 'First Owner'], dtype=object)]

In [35]:
transformers.output_indices_

{'ordinal': slice(0, 1, None),
 'onehot': slice(1, 25, None),
 'remainder': slice(25, 26, None)}

In [36]:
transformers.named_transformers_['onehot'].feature_name_combiner

'concat'